org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.nonTransitiveRClass=true

sdlpop.repo=https://github.com/NagyD/SDLPoP.git
sdlpop.ref=3c5add5fb7f83d4ceb542823ab66d00146c4271b
sdl2.repo=https://github.com/libsdl-org/SDL.git
sdl2.ref=release-2.32.10
sdl2Image.repo=https://github.com/libsdl-org/SDL_image.git
sdl2Image.ref=release-2.8.12
